from typing import Iterator, List, Literal, Optional, Tuple, Union

Kind = Literal["literal", "string", "expr", "list", "block"]
ListElement = Union[str, Tuple[str, "ListElement"], List["ListElement"]]
Scalar = Union[str, bool, int, float]
Assignable = Union[Scalar, List[ListElement], Tuple[ListElement, ...], dict]
PyValue = Union[str, List[ListElement], None]

class LookmlSyntaxError(ValueError):
    line: int
    column: int
    offset: int

class _Container:
    @property
    def children(self) -> List[Pair]: ...
    def find(self, key: str, name: Optional[str] = None) -> Optional[Pair]: ...
    def find_all(self, key: str, name: Optional[str] = None) -> List[Pair]: ...
    def get(self, key: str, default: object = None) -> PyValue: ...
    def add(
        self,
        key: str,
        value: Optional[Assignable] = None,
        *,
        name: Optional[str] = None,
        kind: Optional[Kind] = None,
        index: Optional[int] = None,
    ) -> Pair: ...
    def add_source(self, source: str, index: Optional[int] = None) -> List[Pair]: ...
    def remove(self, target: Union[Pair, str], name: Optional[str] = None) -> bool: ...
    def walk(self) -> List[Pair]: ...
    def __getitem__(self, key: str) -> PyValue: ...
    def __setitem__(self, key: str, value: Assignable) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Pair]: ...

class Document(_Container):
    @staticmethod
    def parse(source: str) -> Document: ...
    def to_string(self) -> str: ...

class Pair(_Container):
    key: str
    name: Optional[str]
    value: PyValue
    comments: List[str]
    @property
    def kind(self) -> Kind: ...
    @property
    def parent(self) -> Union[Document, Pair, None]: ...
    def set_value(self, value: Assignable, kind: Optional[Kind] = None) -> None: ...
    def detach(self) -> bool: ...
    def to_string(self, include_leading: bool = False) -> str: ...

def parse_lookml(source: str) -> Document: ...
